FROM node:alpine


# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY . ./
RUN npm install
RUN npm install react-script
RUN npm run build

WORKDIR /app/build

# start app
CMD ["npm", "start"]